name: Custom .net build action
description: A custom action to build a .NET project

inputs:
  configuration:
    description: 'The build configuration (e.g., Release or Debug)'
    required: true
    default: 'Release'

runs:
  using: "node20"
  main: "index.js"