name: Dotnet build composite action
description: A composite action to build a .NET project

runs:
  using: "composite"
  steps:
    - name: setup SDK Azhar
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore
      shell: bash
    
    - name: Build the project
      run: dotnet build
      shell: bash